name: privacy

channels:
  - pytorch
  - conda-forge
  - defaults
  - pyg

dependencies:
  - ase
  - mkl=2022.2.1
  - cudatoolkit=11.1
  - googledrivedownloader
  - h5py
  - jinja2
  - networkx
  - numba
  - numpy
  - pandas
  - pip
  - python=3.8
  - python-louvain
  - pytorch=1.9.1
  - rdflib
  - requests
  - scikit-learn
  - scipy
  - torchaudio
  - torchvision
  - tqdm
  - pytorch-scatter
  - pytorch-sparse
  - pytorch-cluster
  - pytorch-spline-conv
  - pyg
